# Gene Table

In [1]:
import pandas as pd
import mygene
from functools import reduce

In [7]:
# Generate secrecon dataframe
secrecon = pd.read_excel("Input/working_secRecon.xlsx", sheet_name="master_curated_09202021")
secrecon

,Index,Flag,Initials,Edited,GENE SYMBOL,ALIAS,ENSEMBL,ENTREZID,GENENAME,PMID,...,Process 10 Ref,Process 10 Genes,Process 11,Process 11 Mean Score,Process 11 Score SD,Process 11 Score Count,Process 11 Raw Scores,Process 11 Curators,Process 11 Ref,Process 11 Genes
0,44.0,NaN,NaN,HM,A3GALT2,"A3GALT2P,IGB3S,IGBS3S,A3GALT2",ENSG00000184389,127550.0,"alpha 1,3-galactosyltransferase 2","18630988,21873635,23378701",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,45.0,NaN,NaN,HM,A4GALT,"A14GALT,A4GALT1,Gb3S,P(k),P1,P1PK,PK,A4GALT",ENSG00000128274,53947.0,"alpha 1,4-galactosyltransferase (P blood group)","10591208,10747952,10748143,10854428,10993874,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,46.0,NaN,NaN,HM,A4GNT,"alpha4GnT,A4GNT",ENSG00000118017,51146.0,"alpha-1,4-N-acetylglucosaminyltransferase","10430883,11304796,12477932,12594234,15489334,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19.0,NaN,NaN,HM - PD,ABL1,"ABL,BCR-ABL,CHDSKM,JTK7,bcr/abl,c-ABL,c-ABL1,p...",ENSG00000097007,25.0,"ABL proto-oncogene 1, non-receptor tyrosine ki...","10187839,10194451,10212258,10372803,10391249,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,42.0,NaN,NaN,HM,ABL2,"ABLL,ARG,ABL2",ENSG00000143322,27.0,"ABL proto-oncogene 2, non-receptor tyrosine ki...","10521789,10590083,10706884,10892742,11278261,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
910,743.0,NaN,NaN,JT,YOD1,"DUBA8,OTUD2,PRO0907,YOD1",ENSG00000180667,55432.0,YOD1 deubiquitinase,"12477932,14702039,16710414,19322201,19615732,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,NaN,NaN,NaN,JT,USP19,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
914,NaN,NaN,to be edited,108,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Extract all the unique genes
uGenes = secrecon['GENE SYMBOL']

In [11]:
# Create an instance of the MyGeneInfo class
mg = mygene.MyGeneInfo()

# Find which genes are symbol keys
symKEY = mg.querymany(uGenes, scopes='symbol', fields='symbol', species='human')

INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [15]:
# genes that did not map
diff_genes = set(uGenes) - set([x['query'] for x in symKEY if 'notfound' not in x])
diff_genes

{'ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', nan}

In [23]:
# check to see if they match ALIAS key
alias_genes = mg.querymany(diff_genes, scopes='alias', fields='alias', species='human')

INFO:biothings.client:querying 1-6...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:2 input query terms found no hit:	['GALNT19', 'TMED11']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [27]:
# Table to map gene symbols to aliases
IDtype = ['alias', 'ensembl.gene', 'entrezgene', 'name', 'pmid', 'refseq', 'uniprot']
IDtables = {k: pd.DataFrame(mg.querymany(uGenes, scopes='symbol', fields=k, species='human')) for k in IDtype}

INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.
INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.
INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.
INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.
INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.
INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.
INFO:biothings.client:querying 1-915...
INFO:biothings.client:done.
INFO:biothings.client:Finished.
WARNING:biothings.client:4 input query terms found dup hits:	[('HSP90AA4P', 3), ('HSP90AA5P', 2), ('HSP90AB2P', 2), ('HSP90AB4P', 2)]
WARNING:biothings.client:8 input query terms found no hit:	['ALG1L', 'GALNT19', 'GALNT20', 'MICALCL', 'TMED11', 'nan', 'nan', 'nan']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [28]:
IDtables

{'alias':        query     _id     _score  \
 0    A3GALT2  127550  18.807713
 1     A4GALT   53947  18.499306
 2      A4GNT   51146  18.325245
 3       ABL1      25  17.682743
 4       ABL2      27  17.656471
 ..       ...     ...        ...
 915     YOD1   55432  17.776705
 916    USP19   10869  17.654112
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                  alias notfound
 0                            [A3GALT2P, IGB3S, IGBS3S]      NaN
 1         [A14GALT, A4GALT1, Gb3S, P(k), P1, P1PK, PK]      NaN
 2                                            alpha4GnT      NaN
 3    [ABL, BCR-ABL, CHDSKM, JTK7, bcr/abl, c-ABL, c...      NaN
 4                                          [ABLL, ARG]      NaN
 ..                                                 ...      ...
 915                            [DUBA8, OTUD2, PRO0907]      NaN
 916                                             ZMYND9      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'ensembl.gene':        query     _id     _score                      ensembl notfound
 0    A3GALT2  127550  18.857475  {'gene': 'ENSG00000184389'}      NaN
 1     A4GALT   53947  18.463380  {'gene': 'ENSG00000128274'}      NaN
 2      A4GNT   51146  18.325245  {'gene': 'ENSG00000118017'}      NaN
 3       ABL1      25  17.682743  {'gene': 'ENSG00000097007'}      NaN
 4       ABL2      27  17.652805  {'gene': 'ENSG00000143322'}      NaN
 ..       ...     ...        ...                          ...      ...
 915     YOD1   55432  17.773085  {'gene': 'ENSG00000180667'}      NaN
 916    USP19   10869  17.654465  {'gene': 'ENSG00000172046'}      NaN
 917      nan     NaN        NaN                          NaN     True
 918      nan     NaN        NaN                          NaN     True
 919      nan     NaN        NaN                          NaN     True

 [920 rows x 5 columns],
 'entrezgene':        query     _id     _score entrezgene notfound
 0    A3GALT2  127550  18.807713     127550      NaN
 1     A4GALT   53947  18.493698      53947      NaN
 2      A4GNT   51146  18.326262      51146      NaN
 3       ABL1      25  17.682743         25      NaN
 4       ABL2      27  17.644224         27      NaN
 ..       ...     ...        ...        ...      ...
 915     YOD1   55432  17.774382      55432      NaN
 916    USP19   10869  17.665997      10869      NaN
 917      nan     NaN        NaN        NaN     True
 918      nan     NaN        NaN        NaN     True
 919      nan     NaN        NaN        NaN     True

 [920 rows x 5 columns],
 'name':        query     _id     _score  \
 0    A3GALT2  127550  18.851204
 1     A4GALT   53947  18.508541
 2      A4GNT   51146  18.331810
 3       ABL1      25  17.677670
 4       ABL2      27  17.652805
 ..       ...     ...        ...
 915     YOD1   55432  17.762660
 916    USP19   10869  17.651367
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                   name notfound
 0                    alpha 1,3-galactosyltransferase 2      NaN
 1      alpha 1,4-galactosyltransferase (P blood group)      NaN
 2            alpha-1,4-N-acetylglucosaminyltransferase      NaN
 3    ABL proto-oncogene 1, non-receptor tyrosine ki...      NaN
 4    ABL proto-oncogene 2, non-receptor tyrosine ki...      NaN
 ..                                                 ...      ...
 915                                YOD1 deubiquitinase      NaN
 916                    ubiquitin specific peptidase 19      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'pmid':        query     _id     _score notfound
 0    A3GALT2  127550  18.854883      NaN
 1     A4GALT   53947  18.508541      NaN
 2      A4GNT   51146  18.333622      NaN
 3       ABL1      25  17.676634      NaN
 4       ABL2      27  17.654703      NaN
 ..       ...     ...        ...      ...
 915     YOD1   55432  17.773085      NaN
 916    USP19   10869  17.654465      NaN
 917      nan     NaN        NaN     True
 918      nan     NaN        NaN     True
 919      nan     NaN        NaN     True

 [920 rows x 4 columns],
 'refseq':        query     _id     _score  \
 0    A3GALT2  127550  18.865435
 1     A4GALT   53947  18.488348
 2      A4GNT   51146  18.333105
 3       ABL1      25  17.676634
 4       ABL2      27  17.656471
 ..       ...     ...        ...
 915     YOD1   55432  17.776705
 916    USP19   10869  17.654112
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                 refseq notfound
 0    {'genomic': ['NC_000001.11', 'NC_060925.1', 'N...      NaN
 1    {'genomic': ['NC_000022.11', 'NC_060946.1', 'N...      NaN
 2    {'genomic': ['NC_000003.12', 'NC_060927.1'], '...      NaN
 3    {'genomic': ['NC_000009.12', 'NC_060933.1', 'N...      NaN
 4    {'genomic': ['NC_000001.11', 'NC_060925.1', 'N...      NaN
 ..                                                 ...      ...
 915  {'genomic': ['NC_000001.11', 'NC_060925.1'], '...      NaN
 916  {'genomic': ['NC_000003.12', 'NC_060927.1', 'N...      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'uniprot':        query     _id     _score  \
 0    A3GALT2  127550  18.807713
 1     A4GALT   53947  18.499575
 2      A4GNT   51146  18.333105
 3       ABL1      25  17.677670
 4       ABL2      27  17.652805
 ..       ...     ...        ...
 915     YOD1   55432  17.770678
 916    USP19   10869  17.662292
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                uniprot notfound
 0                             {'Swiss-Prot': 'U3KPV4'}      NaN
 1     {'Swiss-Prot': 'Q9NPC4', 'TrEMBL': 'A0A0S2Z5J1'}      NaN
 2                             {'Swiss-Prot': 'Q9UNA3'}      NaN
 3    {'Swiss-Prot': 'P00519', 'TrEMBL': ['Q59FK4', ...      NaN
 4                             {'Swiss-Prot': 'P42684'}      NaN
 ..                                                 ...      ...
 915                           {'Swiss-Prot': 'Q5VVQ6'}      NaN
 916  {'Swiss-Prot': 'O94966', 'TrEMBL': ['A0A8V8TN9...      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns]}

In [29]:
# Add uGenes into the IDtables dictionary
IDtables['geneList'] = pd.DataFrame({"SYMBOL": uGenes})

In [30]:
IDtables

{'alias':        query     _id     _score  \
 0    A3GALT2  127550  18.807713
 1     A4GALT   53947  18.499306
 2      A4GNT   51146  18.325245
 3       ABL1      25  17.682743
 4       ABL2      27  17.656471
 ..       ...     ...        ...
 915     YOD1   55432  17.776705
 916    USP19   10869  17.654112
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                  alias notfound
 0                            [A3GALT2P, IGB3S, IGBS3S]      NaN
 1         [A14GALT, A4GALT1, Gb3S, P(k), P1, P1PK, PK]      NaN
 2                                            alpha4GnT      NaN
 3    [ABL, BCR-ABL, CHDSKM, JTK7, bcr/abl, c-ABL, c...      NaN
 4                                          [ABLL, ARG]      NaN
 ..                                                 ...      ...
 915                            [DUBA8, OTUD2, PRO0907]      NaN
 916                                             ZMYND9      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'ensembl.gene':        query     _id     _score                      ensembl notfound
 0    A3GALT2  127550  18.857475  {'gene': 'ENSG00000184389'}      NaN
 1     A4GALT   53947  18.463380  {'gene': 'ENSG00000128274'}      NaN
 2      A4GNT   51146  18.325245  {'gene': 'ENSG00000118017'}      NaN
 3       ABL1      25  17.682743  {'gene': 'ENSG00000097007'}      NaN
 4       ABL2      27  17.652805  {'gene': 'ENSG00000143322'}      NaN
 ..       ...     ...        ...                          ...      ...
 915     YOD1   55432  17.773085  {'gene': 'ENSG00000180667'}      NaN
 916    USP19   10869  17.654465  {'gene': 'ENSG00000172046'}      NaN
 917      nan     NaN        NaN                          NaN     True
 918      nan     NaN        NaN                          NaN     True
 919      nan     NaN        NaN                          NaN     True

 [920 rows x 5 columns],
 'entrezgene':        query     _id     _score entrezgene notfound
 0    A3GALT2  127550  18.807713     127550      NaN
 1     A4GALT   53947  18.493698      53947      NaN
 2      A4GNT   51146  18.326262      51146      NaN
 3       ABL1      25  17.682743         25      NaN
 4       ABL2      27  17.644224         27      NaN
 ..       ...     ...        ...        ...      ...
 915     YOD1   55432  17.774382      55432      NaN
 916    USP19   10869  17.665997      10869      NaN
 917      nan     NaN        NaN        NaN     True
 918      nan     NaN        NaN        NaN     True
 919      nan     NaN        NaN        NaN     True

 [920 rows x 5 columns],
 'name':        query     _id     _score  \
 0    A3GALT2  127550  18.851204
 1     A4GALT   53947  18.508541
 2      A4GNT   51146  18.331810
 3       ABL1      25  17.677670
 4       ABL2      27  17.652805
 ..       ...     ...        ...
 915     YOD1   55432  17.762660
 916    USP19   10869  17.651367
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                   name notfound
 0                    alpha 1,3-galactosyltransferase 2      NaN
 1      alpha 1,4-galactosyltransferase (P blood group)      NaN
 2            alpha-1,4-N-acetylglucosaminyltransferase      NaN
 3    ABL proto-oncogene 1, non-receptor tyrosine ki...      NaN
 4    ABL proto-oncogene 2, non-receptor tyrosine ki...      NaN
 ..                                                 ...      ...
 915                                YOD1 deubiquitinase      NaN
 916                    ubiquitin specific peptidase 19      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'pmid':        query     _id     _score notfound
 0    A3GALT2  127550  18.854883      NaN
 1     A4GALT   53947  18.508541      NaN
 2      A4GNT   51146  18.333622      NaN
 3       ABL1      25  17.676634      NaN
 4       ABL2      27  17.654703      NaN
 ..       ...     ...        ...      ...
 915     YOD1   55432  17.773085      NaN
 916    USP19   10869  17.654465      NaN
 917      nan     NaN        NaN     True
 918      nan     NaN        NaN     True
 919      nan     NaN        NaN     True

 [920 rows x 4 columns],
 'refseq':        query     _id     _score  \
 0    A3GALT2  127550  18.865435
 1     A4GALT   53947  18.488348
 2      A4GNT   51146  18.333105
 3       ABL1      25  17.676634
 4       ABL2      27  17.656471
 ..       ...     ...        ...
 915     YOD1   55432  17.776705
 916    USP19   10869  17.654112
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                 refseq notfound
 0    {'genomic': ['NC_000001.11', 'NC_060925.1', 'N...      NaN
 1    {'genomic': ['NC_000022.11', 'NC_060946.1', 'N...      NaN
 2    {'genomic': ['NC_000003.12', 'NC_060927.1'], '...      NaN
 3    {'genomic': ['NC_000009.12', 'NC_060933.1', 'N...      NaN
 4    {'genomic': ['NC_000001.11', 'NC_060925.1', 'N...      NaN
 ..                                                 ...      ...
 915  {'genomic': ['NC_000001.11', 'NC_060925.1'], '...      NaN
 916  {'genomic': ['NC_000003.12', 'NC_060927.1', 'N...      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'uniprot':        query     _id     _score  \
 0    A3GALT2  127550  18.807713
 1     A4GALT   53947  18.499575
 2      A4GNT   51146  18.333105
 3       ABL1      25  17.677670
 4       ABL2      27  17.652805
 ..       ...     ...        ...
 915     YOD1   55432  17.770678
 916    USP19   10869  17.662292
 917      nan     NaN        NaN
 918      nan     NaN        NaN
 919      nan     NaN        NaN

                                                uniprot notfound
 0                             {'Swiss-Prot': 'U3KPV4'}      NaN
 1     {'Swiss-Prot': 'Q9NPC4', 'TrEMBL': 'A0A0S2Z5J1'}      NaN
 2                             {'Swiss-Prot': 'Q9UNA3'}      NaN
 3    {'Swiss-Prot': 'P00519', 'TrEMBL': ['Q59FK4', ...      NaN
 4                             {'Swiss-Prot': 'P42684'}      NaN
 ..                                                 ...      ...
 915                           {'Swiss-Prot': 'Q5VVQ6'}      NaN
 916  {'Swiss-Prot': 'O94966', 'TrEMBL': ['A0A8V8TN9...      NaN
 917                                                NaN     True
 918                                                NaN     True
 919                                                NaN     True

 [920 rows x 5 columns],
 'geneList':       SYMBOL
 0    A3GALT2
 1     A4GALT
 2      A4GNT
 3       ABL1
 4       ABL2
 ..       ...
 910     YOD1
 911    USP19
 912      NaN
 913      NaN
 914      NaN

 [915 rows x 1 columns]}

In [32]:
import pyreadr

In [33]:
result = pyreadr.read_r('geneTable.RDS')

In [34]:
result

OrderedDict([(None,
                    SYMBOL                                              ALIAS  \
              0    A3GALT2                      A3GALT2P,IGB3S,IGBS3S,A3GALT2
              1     A4GALT        A14GALT,A4GALT1,Gb3S,P(k),P1,P1PK,PK,A4GALT
              2      A4GNT                                    alpha4GnT,A4GNT
              3       ABL1  ABL,BCR-ABL,CHDSKM,JTK7,bcr/abl,c-ABL,c-ABL1,p...
              4       ABL2                                      ABLL,ARG,ABL2
              ..       ...                                                ...
              904    XYLT1       DBQD2,PXYLT1,XT-I,XT1,XTI,XYLTI,xylT-I,XYLT1
              905    XYLT2                 PXYLT2,SOS,XT-II,XT2,xylT-II,XYLT2
              906     YKT6                                               YKT6
              907     YOD1                           DUBA8,OTUD2,PRO0907,YOD1
              908    USP19                                       ZMYND9,USP19

                                           ENSEMBL ENTREZID  \
              0                    ENSG00000184389   127550
              1                    ENSG00000128274    53947
              2                    ENSG00000118017    51146
              3                    ENSG00000097007       25
              4                    ENSG00000143322       27
              ..                               ...      ...
              904  ENSG00000103489,ENSG00000285395    64131
              905                  ENSG00000015532    64132
              906                  ENSG00000106636    10652
              907                  ENSG00000180667    55432
              908                  ENSG00000172046    10869

                                                            GENENAME  \
              0                    alpha 1,3-galactosyltransferase 2
              1      alpha 1,4-galactosyltransferase (P blood group)
              2            alpha-1,4-N-acetylglucosaminyltransferase
              3    ABL proto-oncogene 1, non-receptor tyrosine ki...
              4    ABL proto-oncogene 2, non-receptor tyrosine ki...
              ..                                                 ...
              904                               xylosyltransferase 1
              905                               xylosyltransferase 2
              906                               YKT6 v-SNARE homolog
              907                                YOD1 deubiquitinase
              908                    ubiquitin specific peptidase 19

                                                                PMID  \
              0                  18630988,21873635,23378701,31762063
              1    10591208,10747952,10748143,10854428,10993874,1...
              2    8125298,10430883,11304796,12477932,12594234,15...
              3    1281542,1379745,1383690,1505033,1538749,157153...
              4    1383690,2198571,3787260,8125298,8194526,870054...
              ..                                                 ...
              904  10383739,11087729,11099377,11814476,12477932,1...
              905  8889548,9588955,10383739,11087729,11099377,118...
              906  8125298,9211930,11474112,11884350,11927603,123...
              907  7644498,12477932,14702039,16710414,19322201,19...
              908  10048485,12477932,12838346,15302935,16226712,1...

                                                              REFSEQ  \
              0                            NM_001080438,NP_001073907
              1    NM_001318038,NM_017436,NP_001304967,NP_059132,...
              2    NM_016161,NP_057245,XM_017006543,XM_017006544,...
              3              NM_005157,NM_007313,NP_005148,NP_009297
              4    NM_001136000,NM_001136001,NM_001168236,NM_0011...
              ..                                                 ...
              904  NM_022166,NP_071449,XM_017023539,XM_017023540,...
              905  NM_022167,NP_071450,NR_110010,XM_005257572,XP_...
              906  NM_001363678,NM_006555,NP_001350607,NP_006546,...
              907      NM_001276320,NM_018566,NP_001263249,NP_061036
              908  NM_001199160,NM_001199161,NM_001199162,NM_0013...

                                    UNIPROT
              0                      U3KPV4
              1           A0A0S2Z5J1,Q9NPC4
              2                      Q9UNA3
              3    A0A024R8E2,P00519,Q59FK4
              4                      P42684
              ..                        ...
              904                    Q86Y38
              905             B4DT06,Q9H1B5
              906             A4D2J0,O15498
              907                    Q5VVQ6
              908                    O94966

              [909 rows x 8 columns])])